### ISSUE TITLE
feedback to terminal/stderr requested

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#12]
I'm running dare map, project wide, with multiple runs.  This creates maps of the data for each run.
on the command line, the response hangs but i can see if another terminal that the maps are being generated one-by-one

requesting some feedback to the terminal so it is clear that the process is moving foward
eg.
generating map for run xxxxxx1
generating map for run xxxxxx2
etc

**Comment by rjovelin** [comment]
Print status to terminal to indicate:

- when files are extracted from File Provenance Report
- when files are linked to a sequencing run folder
- when md5sums summary files are generated
- when sample maps are generated
