### ISSUE TITLE
ensure that the same file provenance report is used for each dare.py instance

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#15]
throughout the code, FPR is parsed by using the latest report
/.mounts/labs/seqprodbio/private/backups/seqware_files_report_latest.tsv.gz

this may be accessed multiple times each time dare.py is called
it is possible that the latest report might change between calls to this file

to ensure that all data from any dare.py run is from the same FPR
1. dereference the latest link to the source file (which should be date stamped)
2. run all calls to FPR from on that file

it might make sense to emit the report to stderr as well, so this could be captured in a log if generated.  

-----

in addtion, it might make sense to pass FPR as an argument, with the latest as the current one to use.
this would allow one to map from 
1. an older report
2. a modified report (I often generate a smaller local version subsetted by a specific project, when doing multiple calls to the report, as it is much faster)

**Comment by rjovelin** [comment]
- FPR is now an argument to dare link, map, mark and report
- the link is dereferenced and any calls to FPR is using the real path of the same report within each dare submodule
- the path to the FPR used is reported to stdout

I am not sure if using different FPR may create some issues.
However,  it's worth keeping in mind that each submodule parses FPR to retrieve some information.  And that marking files in nabu or generating a report might be done long after the files were linked so it could be unclear which FPR was used for linking the files
