### ISSUE TITLE
dare mark doesn't appear to allow comments on the marked records

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#2]
my process has to been to mark records as pass/fail and then reference a Jira ticket

I tried the dare.py script. it works on a directory of files/links that i've released, which is convenient.
but i don't see a way to include information on what i would like to place in the comment field

**Comment by rjovelin** [comment]
added a -c / --comment parameter to tag the released files with a comment, for instance the Jira ticket.
The same comment is applied to all files under a same directory.
