### ISSUE TITLE
Use absolute paths when symlinking

### ISSUE THREAD

**Issue by morgantaschuk** [oicr-gsi/data_release#38]
Hi Richard,
In the process of archiving files, I create a mock FPR with relative file path locations. This sadly breaks dare's link function.

```
lrwxrwxrwx 1 mtaschuk root 138 Apr 18 16:16 SWID_14011075_PFEM_0015_Bn_P_PE_629_WG_00-3743_190412_A00469_0034_BHJJKFDSXX_SI-GA-E2_L003_R1_001.fastq.gz -> chromium_mkfastq/1.0.0/14011080/SWID_14011075_PFEM_0015_Bn_P_PE_629_WG_00-3743_190412_A00469_0034_BHJJKFDSXX_SI-GA-E2_L003_R1_001.fastq.gz
```

Can you make it so that `link` accepts a prefix for relative links?

**Comment by rjovelin** [comment]
Added flag `-px` to `link`, `map`  and `report` sub-modules to add an optional prefix when FPR contains relative paths.
The absolute file path is then resolved by adding the prefix to the relative file path in FPR.
