### ISSUE TITLE
Make md5sum files functional

### ISSUE THREAD

**Issue by morgantaschuk** [oicr-gsi/data_release#40]
Hi,

When doing dare link, the md5sum files that are generated are not usable immediately.

1. The format is incorrect. it should be md5sum filename, not filename md5sum.
2. the md5sum file is written outside the directory

Ideally, I could be able to go:

```
dare link ...
md5sum -c *md5sums
```

Thanks

**Comment by rjovelin** [comment]
I corrected the format of the md5sum file:
md5sum file_path

The md5sum file is written in the project directory defined by `-p` and `-n` flags.
