### ISSUE TITLE
Generating report in non-default location results in pdf files without plot images 

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#53]
i ran this with the -p option, to generate a report in a local folder and not the default.
The reports were generated and look fine other than the images missing

**Comment by rjovelin** [comment]
`-p` should be the full path to the projects directory. By default is it `/.mounts/labs/gsiprojects/gsi/Data_Transfer/Release/PROJECTS`

The images are missing because a relative path of the figure files is added to the html instead of the full path
