### ISSUE TITLE
dare.py, indicated Nabu is not available

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#6]
i am trying to mark released data, and get back an error
>dare mark -rl pass -u lheisler -d 201120_A00469_0133_BHVFCHDMXX                                          
Traceback (most recent call last):
  File "/.mounts/labs/gsi/modulator/sw/Ubuntu18.04/dare-1.0.0/bin/../share/dare.py", line 611, in <module>
    args.func(args)
  File "/.mounts/labs/gsi/modulator/sw/Ubuntu18.04/dare-1.0.0/bin/../share/dare.py", line 538, in mark_files_nabu
    run = run[:run.index('.')]
ValueError: substring not found

====
i believe this is happening because nabu is down.

Can this be checked in the code, and if nabu is unavailable, have the script fail and report that the service is not available

**Comment by rjovelin** [comment]
The expected format for the directory is run.fastqs (or generally run.suffix. suffix can be a specific workflow/analysis).
The expected command looks like:
dare mark -rl pass -u lheisler -d 201120_A00469_0133_BHVFCHDMXX.fastqs

**Comment by lheisler** [comment]
got it, thanks Richard, that fixes it

can the script check for this and give back a more meaningful error?

**Comment by rjovelin** [comment]
made some edits to:

- check that the input directory is indeed a valid directory
- allow dot "." to be missing from the directory name. ie handles directory names with or without suffix
- extracts the run_id from the directrory name: requires the directory to contain the run id (ie run_id or run_id.suffix)
- raise error if FPR cannot be parsed with the run_id and print out explicit statement and run_id used
