### ISSUE TITLE
dare mark, modification to output to terminal

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#8]
when dare mark is run, in provides feedback to the terminal as 1. accession 2. status (SUCCESS).
currently this looks like this
15807644
SUCCESS15807201
SUCCESS15807885
SUCCESS15807683
SUCCESS

suggesting, for clairty, that the status should follow the accession direct;y, or a new line after SUCCESS

eg
15807644 SUCCESS
15807201 SUCCESS
15807885 SUCCESS
15807683 SUCCESS
15807580 SUCCESS

**Comment by rjovelin** [comment]
Modified dare so it does not depend on nabu.pl anymore.
Changed statements printed to terminal:
Sucessfully updated ```file_swid``` status to ```QC_status``` if success or
Could not update ```file_swid``` status if fail
