### ISSUE TITLE
dare mark : indicate any files in the directory that are being released as NOT being found in nabu

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/data_release#9]
see notes on
https://jira.oicr.on.ca/browse/GDR-430

dare mark relies on paths in a directory to identify which records to mark as pass
if these files are not found in nabu, dare is silent.   
it would be better if it could be reported back, especially in cases where only a subset of the files are missing.
(in cases where all are missing, it is more obvious)

**Comment by rjovelin** [comment]
dare mark gets the swids of the files present in the release directory from FPR.
It now reports back if the file swid cannot be retrieved for some reason.
It also prints a clear message that include the HTTP response code if the file record cannot be modified in Nabu
